export const environment = {
  production: false,
  supabaseUrl:"https://nwwlberkzgpyuchkxcfd.supabase.co",
  supabaseKey:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53d2xiZXJremdweXVjaGt4Y2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTUzMDYsImV4cCI6MjA2MDY3MTMwNn0.ySWVWDeXlT2bQgoOhl76ar8PvpjjDvFnFu3bnyyRmtQ",
  stripePublishableKey:"pk_test_51RIitN2fFfXTvxCk0OLeG2vgUmV833vWSTKdtH3uo3QBQQ4i8D9RhDxBwu2sXM1gOovZlJQKN4fTjumV8TjKkxi800BRFI1uPG"
};
